### ISSUE TITLE
egui shutdown not graceful

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2421]
may impact apple as well

```
thread 'main' panicked at clients/egui/src/account/mod.rs:100:14:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: <lockbook_egui::Lockbook as eframe::epi::App>::on_close_event
   4: eframe::native::epi_integration::EpiIntegration::on_event
   5: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::on_event
   6: eframe::native::run::run_and_return::{{closure}}
   7: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
   8: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
   9: winit::platform_impl::platform::app_state::AppState::cleared
  10: std::panicking::try
  11: winit::platform_impl::platform::observer::control_flow_end_handler
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: eframe::native::run::with_event_loop
  23: eframe::run_native
  24: lockbook_egui::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tvanderstad** [comment]
closed by https://github.com/lockbook/lockbook/pull/4988
