### ISSUE TITLE
editor undo crash

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#2991]
I wasn't doing anything interesting when it happened. I think I undid a 'cut' operation.

```
index out of bounds: the len is 865 but the index is 872    0: std::backtrace::Backtrace::create
   1: lb_rs::service::log_service::panic_capture::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_bounds_check
   8: lb_rs::text::buffer::Snapshot::apply_replace
   9: lb_rs::text::buffer::Buffer::undo
```

**Comment by tvanderstad** [comment]
Just experienced an issue where an undo happened when I didn't undo. No unicode characters in my file - only headings, inline code, and bulleted lists as syntax.

**Comment by tvanderstad** [comment]
Just got this crash on branch `async-docs` after replacing the contents of a document with `’`, then undo'ing:
```
panic detected and logged: panicked at libs/lb/lb-rs/src/text/unicode_segs.rs:25:30:
index out of bounds: the len is 2 but the index is 3    0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/backtrace.rs:331:13
   3: lb_rs::service::logging::panic_capture::{{closure}}
             at /Users/travis/Code/lockbook/lockbook/libs/lb/lb-rs/src/service/logging.rs:53:13
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:785:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:659:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:171:18
   8: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   9: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
  10: core::panicking::panic_bounds_check
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:208:5
  11: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/slice/index.rs:255:10
  12: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/slice/index.rs:18:15
  13: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/vec/mod.rs:2771:9
  14: lb_rs::text::unicode_segs::UnicodeSegs::offset_to_byte
             at /Users/travis/Code/lockbook/lockbook/libs/lb/lb-rs/src/text/unicode_segs.rs:25:30
  15: lb_rs::text::unicode_segs::UnicodeSegs::range_to_byte
             at /Users/travis/Code/lockbook/lockbook/libs/lb/lb-rs/src/text/unicode_segs.rs:31:36
  16: lb_rs::text::buffer::Snapshot::apply_replace
             at /Users/travis/Code/lockbook/lockbook/libs/lb/lb-rs/src/text/buffer.rs:86:26
  17: lb_rs::text::buffer::Buffer::undo
             at /Users/travis/Code/lockbook/lockbook/libs/lb/lb-rs/src/text/buffer.rs:383:29
  18: workspace_rs::tab::markdown_editor::input::mutation::<impl workspace_rs::tab::markdown_editor::editor::Editor>::calc_operations
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/input/mutation.rs:614:29
  19: workspace_rs::tab::markdown_editor::input::events::<impl workspace_rs::tab::markdown_editor::editor::Editor>::process_events
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/input/events.rs:27:25
  20: workspace_rs::tab::markdown_editor::editor::Editor::show_inner_inner
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:264:13
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  22: egui::containers::frame::Frame::show_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:280:19
  23: egui::containers::frame::Frame::show
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:270:9
  24: workspace_rs::tab::markdown_editor::editor::Editor::show_inner::{{closure}}::{{closure}}::{{closure}}
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:225:34
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  27: egui::ui::Ui::with_layout_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2286:21
  28: egui::ui::Ui::vertical_centered
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2233:9
  29: workspace_rs::tab::markdown_editor::editor::Editor::show_inner::{{closure}}::{{closure}}
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:218:28
  30: egui::containers::scroll_area::ScrollArea::show::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/scroll_area.rs:691:61
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  33: egui::containers::scroll_area::ScrollArea::show_viewport_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/scroll_area.rs:763:21
  34: egui::containers::scroll_area::ScrollArea::show
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/scroll_area.rs:691:9
  35: workspace_rs::tab::markdown_editor::editor::Editor::show_inner::{{closure}}
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:213:42
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  38: egui::containers::frame::Frame::show_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:280:19
  39: egui::containers::frame::Frame::show
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:270:9
  40: workspace_rs::tab::markdown_editor::editor::Editor::show_inner
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:212:14
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  43: egui::ui::Ui::with_layout_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2286:21
  44: egui::ui::Ui::vertical
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2214:9
  45: workspace_rs::tab::markdown_editor::editor::Editor::show
             at /Users/travis/Code/lockbook/lockbook/libs/content/workspace/src/tab/markdown_editor/editor.rs:144:12
  46: core::ops::function::FnOnce::call_once{{vtable.shim}}
  47: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  48: egui::ui::Ui::with_layout_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2286:21
  49: core::ops::function::FnOnce::call_once{{vtable.shim}}
  50: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  51: egui::ui::Ui::with_layout_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2286:21
  52: core::ops::function::FnOnce::call_once{{vtable.shim}}
  53: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  54: egui::ui::Ui::with_layout_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/ui.rs:2286:21
  55: workspace_rs::workspace::Workspace::show
  56: lockbook_egui::account::AccountScreen::update::{{closure}}
             at ./src/account/mod.rs:185:27
  57: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  58: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  59: egui::containers::panel::CentralPanel::show_inside_dyn::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/panel.rs:1104:13
  60: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  61: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2015:9
  62: egui::containers::frame::Frame::show_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:280:19
  63: egui::containers::frame::Frame::show
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/frame.rs:270:9
  64: egui::containers::panel::CentralPanel::show_inside_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/panel.rs:1102:15
  65: egui::containers::panel::CentralPanel::show_dyn
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/panel.rs:1137:30
  66: egui::containers::panel::CentralPanel::show
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/containers/panel.rs:1114:9
  67: lockbook_egui::account::AccountScreen::update
             at ./src/account/mod.rs:173:14
  68: lockbook_egui::Lockbook::update
             at ./src/lib.rs:100:17
  69: <lockbook_egui::Lockbook as eframe::epi::App>::update
             at ./src/lib.rs:112:22
  70: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/epi_integration.rs:317:17
  71: egui::context::Context::run
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/context.rs:753:9
  72: eframe::native::epi_integration::EpiIntegration::update
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/epi_integration.rs:310:27
  73: eframe::native::wgpu_integration::WgpuWinitRunning::run_ui_and_paint
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/wgpu_integration.rs:627:27
  74: <eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/wgpu_integration.rs:385:13
  75: eframe::native::run::run_and_return::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:96:17
  76: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:87:13
  77: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:70:13
  78: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:86:9
  79: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  80: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:647:13
  81: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/observer.rs:78:21
  82: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/observer.rs:40:9
  83: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
  84: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
  85: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
  86: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/event_loop.rs:469:11
  87: winit::platform_impl::platform::observer::control_flow_handler
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/observer.rs:38:5
  88: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/observer.rs:73:9
  89: <unknown>
  90: <unknown>
  91: <unknown>
  92: <unknown>
  93: <unknown>
  94: <unknown>
  95: <unknown>
  96: <unknown>
  97: <unknown>
  98: <unknown>
  99: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/event_loop.rs:310:26
 100: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
 101: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panic/unwind_safe.rs:272:9
 102: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
 103: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
 104: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
 105: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/event_loop.rs:299:32
 106: objc2::rc::autorelease::autoreleasepool
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/rc/autorelease.rs:438:15
 107: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/event_loop.rs:281:9
 108: <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform/run_on_demand.rs:80:9
 109: eframe::native::run::run_and_return
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:73:5
 110: eframe::native::run::run_wgpu::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:424:13
 111: eframe::native::run::with_event_loop::{{closure}}
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:58:12
 112: std::thread::local::LocalKey<T>::try_with
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/thread/local.rs:286:16
 113: std::thread::local::LocalKey<T>::with
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/thread/local.rs:262:9
 114: eframe::native::run::with_event_loop
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:48:16
 115: eframe::native::run::run_wgpu
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:422:16
 116: eframe::run_native
             at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/lib.rs:268:13
 117: lockbook_egui::main
             at ./src/main.rs:42:5
 118: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
 119: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:155:18
 120: std::rt::lang_start::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:166:18
 121: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:284:13
 122: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
 123: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
 124: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
 125: std::rt::lang_start_internal::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:148:48
 126: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
 127: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
 128: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
 129: std::rt::lang_start_internal
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:148:20
 130: _main
```

**Comment by tvanderstad** [comment]
Minimal reproduction: new doc -> paste any multi-byte unicode char -> undo -> app crashes
