### ISSUE TITLE
search broken on PR 'core: bring tokio to core'

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#3000]
1. Building the search index does not complete (or even start) before the search is executed, so your first search always comes up empty
2. Building the search index fails with FileNonexistent which is unwrapped, crashing the egui app (this went away on clean install and may be unrelated)
```
panic detected and logged: panicked at clients/egui/src/account/full_doc_search.rs:86:62:
called `Result::unwrap()` on an `Err` value: LbErr { kind: FileNonexistent, backtrace: Some(Backtrace [{ fn: "std::backtrace::Backtrace::create" }, { fn: "lb_rs::service::file::<impl lb_rs::Lb>::get_file_by_id::{{closure}}" }, { fn: "tokio::runtime::park::CachedParkThread::block_on" }, { fn: "tokio::runtime::context::runtime::enter_runtime" }, { fn: "tokio::runtime::runtime::Runtime::block_on" }, { fn: "lb_rs::blocking::Lb::get_file_by_id" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "egui::ui::Ui::with_layout_dyn" }, { fn: "lockbook_egui::account::full_doc_search::FullDocSearch::show_results" }, { fn: "egui::containers::scroll_area::ScrollArea::show" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "egui::ui::Ui::with_layout_dyn" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "egui::ui::Ui::with_layout_dyn" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "egui::ui::Ui::with_layout_dyn" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "egui::containers::panel::SidePanel::show_dyn" }, { fn: "egui::containers::panel::SidePanel::show_animated" }, { fn: "lockbook_egui::account::AccountScreen::update" }, { fn: "lockbook_egui::Lockbook::update" }, { fn: "<lockbook_egui::Lockbook as eframe::epi::App>::update" }, { fn: "<eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint" }, { fn: "eframe::native::run::run_and_return::{{closure}}" }, { fn: "<winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event" }, { fn: "winit::platform_impl::platform::app_state::Handler::handle_nonuser_event" }, { fn: "winit::platform_impl::platform::app_state::AppState::cleared" }, { fn: "std::panicking::try" }, { fn: "winit::platform_impl::platform::observer::control_flow_end_handler" }, { fn: "std::panicking::try" }, { fn: "winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand" }, { fn: "eframe::native::run::run_wgpu" }, { fn: "eframe::run_native" }, { fn: "lockbook_egui::main" }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace" }, { fn: "std::rt::lang_start::{{closure}}" }, { fn: "std::rt::lang_start_internal" }, { fn: "_main" }]) }    0: std::backtrace::Backtrace::create
   1: lb_rs::service::logging::panic_capture::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: egui::ui::Ui::with_layout_dyn
  10: lockbook_egui::account::full_doc_search::FullDocSearch::show_results
  11: egui::containers::scroll_area::ScrollArea::show
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: egui::ui::Ui::with_layout_dyn
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: egui::ui::Ui::with_layout_dyn
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: egui::ui::Ui::with_layout_dyn
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: egui::containers::panel::SidePanel::show_dyn
  21: egui::containers::panel::SidePanel::show_animated
  22: lockbook_egui::account::AccountScreen::update
  23: lockbook_egui::Lockbook::update
  24: <lockbook_egui::Lockbook as eframe::epi::App>::update
  25: <eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint
  26: eframe::native::run::run_and_return::{{closure}}
  27: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
  28: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  29: winit::platform_impl::platform::app_state::AppState::cleared
  30: std::panicking::try
  31: winit::platform_impl::platform::observer::control_flow_end_handler
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: std::panicking::try
  43: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
  44: eframe::native::run::run_wgpu
  45: eframe::run_native
  46: lockbook_egui::main
  47: std::sys_common::backtrace::__rust_begin_short_backtrace
  48: std::rt::lang_start::{{closure}}
  49: std::rt::lang_start_internal
  50: _main

panic detected and logged: panicked at /Users/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }    0: std::backtrace::Backtrace::create
   1: lb_rs::service::logging::panic_capture::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: winit::platform_impl::platform::app_state::AppState::clear_callback
   9: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
  10: eframe::native::run::run_wgpu
  11: eframe::run_native
  12: lockbook_egui::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal
  16: _main

panic detected and logged: panicked at libs/lb/lb-rs/src/service/search.rs:84:40:
called `Result::unwrap()` on an `Err` value: LbErr { kind: Unexpected("unexpected shared error SharedError { kind: Io(\"background task failed\"), backtrace: Some(Backtrace [{ fn: \"std::backtrace::Backtrace::create\" }, { fn: \"<lb_rs::logic::SharedError as core::convert::From<std::io::error::Error>>::from\" }, { fn: \"lb_rs::repo::docs::AsyncDocs::maybe_get::{{closure}}::{{closure}}\" }, { fn: \"lb_rs::repo::docs::AsyncDocs::get::{{closure}}::{{closure}}\" }, { fn: \"lb_rs::service::search::<impl lb_rs::Lb>::build_index::{{closure}}\" }, { fn: \"lb_rs::service::search::<impl lb_rs::Lb>::search::{{closure}}::{{closure}}\" }, { fn: \"tokio::runtime::task::core::Core<T,S>::poll\" }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll\" }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Context::run_task\" }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Context::run\" }, { fn: \"tokio::runtime::context::runtime::enter_runtime\" }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::run\" }, { fn: \"tokio::runtime::task::core::Core<T,S>::poll\" }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll\" }, { fn: \"tokio::runtime::blocking::pool::Inner::run\" }, { fn: \"std::sys_common::backtrace::__rust_begin_short_backtrace\" }, { fn: \"core::ops::function::FnOnce::call_once{{vtable.shim}}\" }, { fn: \"std::sys::pal::unix::thread::Thread::new::thread_start\" }, { fn: \"__pthread_joiner_wake\" }]) }"), backtrace: Some(Backtrace [{ fn: "std::backtrace::Backtrace::create" }, { fn: "<lb_rs::logic::SharedError as core::convert::From<std::io::error::Error>>::from" }, { fn: "lb_rs::repo::docs::AsyncDocs::maybe_get::{{closure}}::{{closure}}" }, { fn: "lb_rs::repo::docs::AsyncDocs::get::{{closure}}::{{closure}}" }, { fn: "lb_rs::service::search::<impl lb_rs::Lb>::build_index::{{closure}}" }, { fn: "lb_rs::service::search::<impl lb_rs::Lb>::search::{{closure}}::{{closure}}" }, { fn: "tokio::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::Context::run_task" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::Context::run" }, { fn: "tokio::runtime::context::runtime::enter_runtime" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::run" }, { fn: "tokio::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll" }, { fn: "tokio::runtime::blocking::pool::Inner::run" }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "std::sys::pal::unix::thread::Thread::new::thread_start" }, { fn: "__pthread_joiner_wake" }]) }    0: std::backtrace::Backtrace::create
   1: lb_rs::service::logging::panic_capture::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: lb_rs::service::search::<impl lb_rs::Lb>::search::{{closure}}::{{closure}}
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: std::sys::pal::unix::thread::Thread::new::thread_start
  21: __pthread_joiner_wake
```
3. On a clean install, search fails with 'AccountNonexistent', and the egui app freezes
```
panic detected and logged: panicked at libs/lb/lb-rs/src/service/search.rs:84:40:
called `Result::unwrap()` on an `Err` value: LbErr { kind: AccountNonexistent, backtrace: Some(Backtrace [{ fn: "std::backtrace::Backtrace::create" }, { fn: "lb_rs::service::search::<impl lb_rs::Lb>::build_index::{{closure}}" }, { fn: "lb_rs::service::search::<impl lb_rs::Lb>::search::{{closure}}::{{closure}}" }, { fn: "tokio::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::Context::run_task" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::Context::run" }, { fn: "tokio::runtime::context::runtime::enter_runtime" }, { fn: "tokio::runtime::scheduler::multi_thread::worker::run" }, { fn: "tokio::runtime::task::core::Core<T,S>::poll" }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll" }, { fn: "tokio::runtime::blocking::pool::Inner::run" }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace" }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}" }, { fn: "std::sys::pal::unix::thread::Thread::new::thread_start" }, { fn: "__pthread_joiner_wake" }]) }    0: std::backtrace::Backtrace::create
   1: lb_rs::service::logging::panic_capture::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: lb_rs::service::search::<impl lb_rs::Lb>::search::{{closure}}::{{closure}}
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: std::sys::pal::unix::thread::Thread::new::thread_start
  21: __pthread_joiner_wake
```
4. On a clean install when launching the app having already signed in, search succeeds and is almost fast enough to use synchronously

**Comment by tvanderstad** [comment]
Search works well and decently fast for letters, but when I enter a number with more than one digit it seems to never complete. I am able to sync in the meantime so I don't suspect lock contention. Looking into what's going on...

**Comment by tvanderstad** [comment]
Fixed on the PR
