### ISSUE TITLE
Crash at startup on Android 15

### ISSUE THREAD

**Issue by BuriedInTheGround** [lockbook/lockbook#3043]
The Lockbook app, version 0.9.12, always crashes at startup on my Android 15 device, so I cannot use it at all.

```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024102400:user/release-keys
package: app.lockbook:50
process: app.lockbook
processUptime: 1384 + 196 ms
installer: com.android.vending

kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....label uses attachments with formats [Some(Rgba8UnormSrgb)]


	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:224)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:207)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:47)
	at app.lockbook.workspace.AndroidResponse$$serializer.deserialize(Workspace.kt:39)
	at app.lockbook.workspace.AndroidResponse$$serializer.deserialize(Workspace.kt:39)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:38)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at app.lockbook.util.WorkspaceView.drawWorkspace(WorkspaceView.kt:412)
	at app.lockbook.util.WorkspaceView.draw(WorkspaceView.kt:230)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at androidx.slidingpanelayout.widget.SlidingPaneLayout.drawChild(SlidingPaneLayout.java:1186)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.draw(View.java:24845)
	at androidx.slidingpanelayout.widget.SlidingPaneLayout.draw(SlidingPaneLayout.java:1369)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.updateDisplayListIfDirty(View.java:23683)
	at android.view.View.draw(View.java:24573)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4537)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4298)
	at android.view.View.draw(View.java:24845)
	at com.android.internal.policy.DecorView.draw(DecorView.java:778)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by smailbarkouch** [comment]
Hi @BuriedInTheGround, thank you for reporting the issue. Me and the team quickly found the cause, and made the necessary fix. You can download the fixed version in the [new release](https://github.com/lockbook/lockbook/releases/tag/0.9.13). If you prefer downloading through Google Play, it will take a second for the new version to be approved by Google.

**Comment by BuriedInTheGround** [comment]
Thank you @smailbarkouch and team for the quick fix! I'll wait for Play Store version.

**Comment by Parth** [comment]
(also intend to make some process changes to make sure such a high severity defect doesn't make it to production)

**Comment by smailbarkouch** [comment]
Hey @BuriedInTheGround, the fix is out on the play store.
