### ISSUE TITLE
linux client via snap crashes on startup with "no suitable GPU adapters found"

### ISSUE THREAD

**Issue by tvanderstad** [lockbook/lockbook#3075]
```sh
~/Code/lockbook/lockbook/clients/linux master ❯ lockbook-desktop
thread 'main' panicked at clients/linux/src/window.rs:409:10:
No suitable GPU adapters found on the system!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tvanderstad** [comment]
In one run of the linux client I got this possibly-related output (then never saw it again)
```
~/Code/lockbook/lockbook/clients/linux master~1 1m  15s ❯ cargo run --release
   Compiling workspace v0.9.13 (/home/travis/Code/lockbook/lockbook/libs/content/workspace)
   Compiling egui_editor v0.9.13 (/home/travis/Code/lockbook/lockbook/libs/content/editor/egui_editor)
   Compiling lockbook-egui v0.9.13 (/home/travis/Code/lockbook/lockbook/clients/egui)
   Compiling lockbook-linux v0.9.13 (/home/travis/Code/lockbook/lockbook/clients/linux)
    Finished release [optimized] target(s) in 18.49s
     Running `/home/travis/Code/lockbook/lockbook/target/release/lockbook-linux`
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI3: Screen seems not DRI3 capable
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
```

**Comment by tvanderstad** [comment]
observed for at least two versions
```
~/Code/lockbook/lockbook/clients/linux master ❯ snap list lockbook-desktop --all
Name              Version  Rev  Tracking       Publisher      Notes
lockbook-desktop  0.9.11   37   latest/stable  smailbarkouch  -
lockbook-desktop  0.9.12   38   latest/stable  smailbarkouch  disabled
~/Code/lockbook/lockbook/clients/linux master ❯ which lockbook-desktop
/snap/bin/lockbook-desktop
~/Code/lockbook/lockbook/clients/linux master ❯ lockbook-desktop
thread 'main' panicked at clients/linux/src/window.rs:409:10:
No suitable GPU adapters found on the system!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~/Code/lockbook/lockbook/clients/linux master ❯ snap refresh lockbook-desktop
lockbook-desktop 0.9.12 from Smail Barkouch (smailbarkouch) refreshed
~/Code/lockbook/lockbook/clients/linux master 7s ❯ snap list lockbook-desktop --all
Name              Version  Rev  Tracking       Publisher      Notes
lockbook-desktop  0.9.11   37   latest/stable  smailbarkouch  disabled
lockbook-desktop  0.9.12   38   latest/stable  smailbarkouch  -
~/Code/lockbook/lockbook/clients/linux master ❯ lockbook-desktop
thread 'main' panicked at clients/linux/src/window.rs:409:10:
No suitable GPU adapters found on the system!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Parth** [comment]
Can you try to update all the packages on your system, reboot and retry please?
