### ISSUE TITLE
Back arrow button crash the app on Android

### ISSUE THREAD

**Issue by BuriedInTheGround** [lockbook/lockbook#3151]
## System info

Device version: Android 15
Lockbook version: 0.9.14

## Issue details

Pressing the back arrow button makes the Android app crash, however only if the keyboard is open. See video.

https://github.com/user-attachments/assets/e4d91269-266d-4324-ac7f-3fb765d30e41

<details>
<summary>Crash report</summary>
```
type: crash
osVersion: google/husky/husky:15/AP3A.241105.007/2024111800:user/release-keys
userType: full.secondary
package: app.lockbook:52, targetSdk 34
process: app.lockbook
processUptime: 4398 + 201 ms
installer: com.android.vending

java.lang.StringIndexOutOfBoundsException: length=502; regionStart=0; regionLength=-1
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:122)
	at android.text.TextUtils.substring(TextUtils.java:362)
	at android.view.inputmethod.BaseInputConnection.getTextAfterCursor(BaseInputConnection.java:629)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$getTextAfterCursor$5(RemoteInputConnectionImpl.java:489)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$9UjqFI5m9SQ-gZZ0VB9SvYbiZ0Y(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda23.get(D8$$SyntheticClass:0)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$dispatchWithTracing$49(RemoteInputConnectionImpl.java:1447)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$2C56kBNyimaX29P3MVRhxNO0E2M(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda35.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
</details>

**Comment by Parth** [comment]
Hey @BuriedInTheGround are you still experiencing this on our latest release? We're doing a pass over all the android errors presently

**Comment by interrato** [comment]
Yes, same exact behavior.

FYI I have not been actively using Lockbook for the past few month (or any other notes app fwiw). Still, I can try to check for errors if you guys need me to.

**Comment by ad-tra** [comment]
hey does this still happen, I wasn't able to reproduce.

**Comment by Parth** [comment]
Hey @BuriedInTheGround this is the last one we've been trying to crush before we release and are struggling to repro on a variety of devices and situations. We sorta have the hint based on that stack trace that we may be hitting some bug within android itself or the keyboard implementation but we want to be sure before we say it's not our problem.
- how did you generate that crash report. Is it from the show details crash dialog that pops up?
- could you give us `debug_info` generated immediately after the crash?
- we may release 0.9.25 without this, we've changed a lot on android so we're also wondering if the problem has worked itself out (and that's why we can't reproduce it).
- Just a shot in the dark, but are there any updates to your keyboard or android itself that you can apply? Does that help the situation?

Maybe we'll be in combing through a log file territory if none of that works.

**Comment by Parth** [comment]
@smailbarkouch / @ad-tra lmk if I missed anything

**Comment by interrato** [comment]
Hey @Parth. Apologies for the long delay, I've been _very_ busy with my master's thesis. 😅 

> how did you generate that crash report. Is it from the show details crash dialog that pops up?

Yes, exactly.

<details>
<summary>Here is the report again, with the latest version of Lockbook, 25.9.17</summary>
<pre><code>type: crash
osVersion: google/husky/husky:16/BP2A.250805.005/2025091900:user/release-keys
userType: full.secondary
package: app.lockbook:68, targetSdk 35
process: app.lockbook
processUptime: 6505 + 298 ms
installer: com.android.vending

java.lang.StringIndexOutOfBoundsException: length=502; regionStart=0; regionLength=-1
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:122)
	at android.text.TextUtils.substring(TextUtils.java:353)
	at android.view.inputmethod.BaseInputConnection.getTextAfterCursor(BaseInputConnection.java:629)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$getTextAfterCursor$5(RemoteInputConnectionImpl.java:524)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$9UjqFI5m9SQ-gZZ0VB9SvYbiZ0Y(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda24.get(D8$$SyntheticClass:0)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$dispatchWithTracing$49(RemoteInputConnectionImpl.java:1482)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$2C56kBNyimaX29P3MVRhxNO0E2M(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda36.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9106)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)</code></pre>
</details>

> could you give us `debug_info` generated immediately after the crash?

I don't think it'll help, since the `last_panic` field is empty. Anyway, here it is, from the "Debug Info" section of the app's Settings. I performed the steps that make Lockbook crash, then immediately reopened the app and copied the info.

<details>
<summary>Debug Info</summary>
<pre><code>{
  "time": "2025-09-23 11:09:19 +02:00",
  "name": "simone",
  "last_synced": "just now",
  "lb_version": "25.9.17",
  "rust_triple": "aarch64.unix.android",
  "os_info": "16.36",
  "lb_dir": "/data/user/14/app.lockbook/files",
  "server_url": "https://api.prod.lockbook.net",
  "integrity": "Ok([EmptyFile(8267eaf7-6710-4ad2-99b8-5a098f745eea), EmptyFile(1434d958-b4c2-446d-be66-808cb6c16327), EmptyFile(1bfb7a76-b323-4e09-82d1-95b94acf8328), EmptyFile(108b6863-42ae-4fe2-92a3-e8d01220598f), EmptyFile(4fc0e25e-2e06-4a45-99e3-69fd759a9f3e), EmptyFile(6cc63775-2145-43f6-9387-78b7e116ff9c), EmptyFile(6709ffd7-d9c4-45b2-9953-0b14e6ad9bf3), EmptyFile(9d76b0ca-d1f8-40be-8524-cd6f14c16284), EmptyFile(427c25a1-9092-444e-9649-2ded746851f7), EmptyFile(f5efd5c9-c8d4-4835-a2ce-d863cbaec7dc), EmptyFile(0458c144-2270-4fa8-8285-3ca8897618ec), EmptyFile(451678ea-469d-4944-a77c-193382828020), EmptyFile(29dd3f58-d2b7-4287-9ad8-24c88ec0c545), EmptyFile(8b81dc4c-caaf-49ef-a1cd-e1980081c291), EmptyFile(7e4c608b-09d7-4d90-8719-b790850414bc), EmptyFile(b7299cf5-6538-478a-a98e-51481da1b465), EmptyFile(fce7cf75-cd3e-4d52-b692-4bc086a197b2), EmptyFile(ca7a6b82-9880-4a29-876a-e26ad440a7d4), EmptyFile(1d4f2d3a-375a-4e4e-9f25-7767e4bd4ada), EmptyFile(f4800354-53d3-4990-8962-0f50a547b88e), EmptyFile(946a83de-18fd-4733-9594-6dfd13763bde), EmptyFile(1384bdbd-0fa1-4185-9e89-e0b770f16e36), EmptyFile(947730ac-c35a-4724-83f2-228254dd1286), EmptyFile(cc939b2d-adb8-41a1-8a39-58555c7aafc9), EmptyFile(af2681f7-addf-4340-bb68-51e74cd904a4), EmptyFile(75c2ed32-5296-4cc0-9b63-b7f60ecfb7f4), EmptyFile(9e25f650-d8c6-4375-816d-707df4a95a98), EmptyFile(5dfcd968-16bc-4c79-a82f-9ab91d116545), EmptyFile(f86dd10b-7a5b-4876-9a68-2ecdea2cac59), EmptyFile(536c5efb-ec37-40ea-9461-2e287a96bb9c), EmptyFile(e7f00f67-4e76-4c68-ba26-1a4888cf5867), EmptyFile(77a96a78-2354-4c93-91a2-1576af700cae), EmptyFile(31e321f0-54c4-46e2-b077-fa9cad959c77), EmptyFile(5bc265ce-c726-48ec-b7aa-2bc045c1778d), EmptyFile(15948df4-f00b-46a2-bcad-829270784de5)])",
  "log_tail": "busy=8.79µs time.idle=90.7µs\n2025-09-23T09:09:19.356421Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=536c5efb-ec37-40ea-9461-2e287a96bb9c user_activity=false}: lb_rs::service::documents: close time.busy=92.9µs time.idle=713µs\n2025-09-23T09:09:19.356496Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=e7f00f67-4e76-4c68-ba26-1a4888cf5867 user_activity=false}: lb_rs::service::documents: close time.busy=197µs time.idle=1.08ms\n2025-09-23T09:09:19.356587Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=004b87d2-9577-457a-920c-548f66fc3851 user_activity=false}: lb_rs::service::documents: close time.busy=89.3µs time.idle=668µs\n2025-09-23T09:09:19.356672Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=5c555745-d2db-4456-aacb-6357b6e34d87 user_activity=false}: lb_rs::service::documents: close time.busy=228µs time.idle=2.72ms\n2025-09-23T09:09:19.356730Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=bf4d2d5a-ef91-4f95-9c95-0e47f321fcd2 user_activity=false}: lb_rs::service::documents: close time.busy=107µs time.idle=1.67ms\n2025-09-23T09:09:19.356757Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=d5a5abd8-4155-4037-8f6c-72b7dfda5c30 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.356797Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=15948df4-f00b-46a2-bcad-829270784de5 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.356888Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=73687e06-7508-4779-a6f4-d0bc9ac24d35 user_activity=false}: lb_rs::service::documents: close time.busy=157µs time.idle=1.64ms\n2025-09-23T09:09:19.356910Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=faa734dc-431c-44b9-89b4-1b16cb435439 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357002Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=c744a41a-58e6-4357-8664-d290b1afdc4e user_activity=false}: lb_rs::service::documents: close time.busy=85.8µs time.idle=794µs\n2025-09-23T09:09:19.357029Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=095377ac-31ed-4861-a6eb-d7fbe4c47718 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357057Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=aeb5c841-9837-4dc4-b9a5-5479a4ccfd17 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357093Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=77a96a78-2354-4c93-91a2-1576af700cae user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357114Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=77a96a78-2354-4c93-91a2-1576af700cae user_activity=false}: lb_rs::service::documents: close time.busy=4.92µs time.idle=16.7µs\n2025-09-23T09:09:19.357172Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=31e321f0-54c4-46e2-b077-fa9cad959c77 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357195Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=31e321f0-54c4-46e2-b077-fa9cad959c77 user_activity=false}: lb_rs::service::documents: close time.busy=5.98µs time.idle=17.4µs\n2025-09-23T09:09:19.357223Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=a95564cf-e29b-4b47-ab64-47a45ed39f33 user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357327Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=aeb5c841-9837-4dc4-b9a5-5479a4ccfd17 user_activity=false}: lb_rs::service::documents: close time.busy=79.8µs time.idle=190µs\n2025-09-23T09:09:19.357357Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=5bc265ce-c726-48ec-b7aa-2bc045c1778d user_activity=false}: lb_rs::service::documents: new\n2025-09-23T09:09:19.357389Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=5bc265ce-c726-48ec-b7aa-2bc045c1778d user_activity=false}: lb_rs::service::documents: close time.busy=6.43µs time.idle=26.4µs\n2025-09-23T09:09:19.357529Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=d5a5abd8-4155-4037-8f6c-72b7dfda5c30 user_activity=false}: lb_rs::service::documents: close time.busy=82.8µs time.idle=690µs\n2025-09-23T09:09:19.357634Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=625db2ae-9489-404d-ac65-1cd1d22b5605 user_activity=false}: lb_rs::service::documents: close time.busy=172µs time.idle=1.96ms\n2025-09-23T09:09:19.357690Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=15948df4-f00b-46a2-bcad-829270784de5 user_activity=false}: lb_rs::service::documents: close time.busy=71.2µs time.idle=823µs\n2025-09-23T09:09:19.357779Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=095377ac-31ed-4861-a6eb-d7fbe4c47718 user_activity=false}: lb_rs::service::documents: close time.busy=70.5µs time.idle=680µs\n2025-09-23T09:09:19.357869Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=faa734dc-431c-44b9-89b4-1b16cb435439 user_activity=false}: lb_rs::service::documents: close time.busy=90.0µs time.idle=869µs\n2025-09-23T09:09:19.357924Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity:read_document{id=a95564cf-e29b-4b47-ab64-47a45ed39f33 user_activity=false}: lb_rs::service::documents: close time.busy=70.6µs time.idle=631µs\n2025-09-23T09:09:19.358031Z DEBUG debug_info{os_info=\"16.36\"}:test_repo_integrity: lb_rs::service::integrity: close time.busy=26.6ms time.idle=183µs\n",
  "last_panic": ""
}</code></pre>
</details>

> we're also wondering if the problem has worked itself out

Unfortunately, no magical autofix this time. 😅 

> are there any updates to your keyboard or android itself that you can apply?

I have updated my device a minute ago. I am currently on GrapheneOS build 2025091900 with Android 16. The keyboard is the default one, i.e., [a fork of the AOSP keyboard](https://github.com/GrapheneOS/platform_packages_inputmethods_LatinIME). So, everything is up to date.

<details>
<summary>Here is an excerpt from the keyboard app logs (after triggering the crash again)</summary>
<pre><code>--------- beginning of main
09-23 09:20:30.096  6599  6599 I LatinIME: Hardware accelerated drawing: true
09-23 09:20:30.101  6599  6599 W InputAttributes: No editor info for this field. Bug?
09-23 09:20:30.101  6599  6599 I com.android.inputmethod.latin: AssetManager2(0x100c467194d8928) locale list changing from [it-IT] to [it]
09-23 09:20:30.102  6599  6599 I com.android.inputmethod.latin: AssetManager2(0x100c467194d8928) locale list changing from [it] to [it-IT]
09-23 09:20:30.104  6599  6774 I LatinIME:LogUtils: Dictionary info: dictionary = userunigram.it ; version = 1758619230 ; date = ?
09-23 09:20:30.119  6599  6774 I LatinIME:LogUtils: Dictionary info: dictionary = main:it ; version = 54 ; date = 1414726258
--------- switch to events
09-23 09:20:30.123  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=Not drawing due to not visible. Reason=View.INVISIBLE]
--------- switch to main
09-23 09:20:30.130  6599  6599 W RichInputMethodSubtype: Can't find emoji subtype
09-23 09:20:30.130  6599  6599 W RichInputMethodSubtype: No input method subtype found; returning placeholder subtype: Multi-lingual subtype: android.view.inputmethod.InputMethodSubtype@d78b2ed0, zz
09-23 09:20:30.142  6599  6599 I EmojiCategory: Last Emoji category id is 8
09-23 09:20:30.143  6599  6599 W ViewPager: Requested offscreen page limit 0 too small; defaulting to 1
09-23 09:20:30.151  6599  6683 W com.android.inputmethod.latin: Cleared Reference was only reachable from finalizer (only reported once)
09-23 09:21:17.250  6599  6599 I LatinIME: Starting input. Cursor position = 0,0
09-23 09:21:17.294  6599  6599 I com.android.inputmethod.latin: AssetManager2(0x100c467194d8928) locale list changing from [it-IT] to [it]
09-23 09:21:17.295  6599  6599 I com.android.inputmethod.latin: AssetManager2(0x100c467194d8928) locale list changing from [it] to [it-IT]
--------- switch to events
09-23 09:21:17.309  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=Start draw after previous draw not visible]
09-23 09:21:17.360  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=reportDrawFinished seqId=0]
09-23 09:21:17.363  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=reportDrawFinished seqId=0]
09-23 09:21:17.365  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=reportDrawFinished seqId=0]
--------- switch to main
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: getTextAfterCursor() was failed with an exception=java.lang.StringIndexOutOfBoundsException: length=502; regionStart=0; regionLength=-1
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:122)
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: 	at android.text.TextUtils.substring(TextUtils.java:353)
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: 	at android.view.inputmethod.BaseInputConnection.getTextAfterCursor(BaseInputConnection.java:629)
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: 	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$getTextAfterCursor$5(RemoteInputConnectionImpl.java:524)
09-23 09:21:18.746  6599  6599 W RemoteInputConnection: 	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$9UjqFI5m9SQ-gZZ0VB9SvYbiZ0Y(Unknown Source:0)
09-23 09:21:18.925  6599  6599 E IPCThreadState: Binder transaction failure. id: 836382, BR_*: 29189, error: -22 (Invalid argument)
09-23 09:21:18.926  6599  6599 E IPCThreadState: Binder transaction failure. id: 836386, BR_*: 29189, error: -22 (Invalid argument)
--------- switch to system
09-23 09:21:18.926  6599  6599 D ActivityThread: Too many transaction errors, throttling freezer binder callback.
--------- switch to main
09-23 09:21:18.926  6599  6599 I ImeTracker: app.lockbook:1debc8f8: onHidden
--------- switch to system
09-23 09:21:19.007  6599  6599 D ActivityThread: Too many transaction errors, throttling freezer binder callback.
--------- switch to events
09-23 09:21:19.452  6599  6599 I viewroot_draw_event: [window=VRI[InputMethod],event=Not drawing due to not visible. Reason=View.GONE]</code></pre>
</details>

I'm not sure how else I can help. If you have any ideas, I can try.
