### ISSUE TITLE
Get kotlin interface tests to work without android sdk

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#552]
The aim is to get rid of the SDK entirely in place of using a something that can be done from the CLI with as little as java. A contender is the junit and hamcrest jar files, they can be used to run the tests without gradle and the android sdk.

**Comment by SmailBarkouch** [comment]
The junit and hamcrest jar files don't seem to be working locally for android, which somewhat makes sense since they weren't really made to work with android tests. A user [here](https://stackoverflow.com/questions/11144466/running-android-junit-tests-from-command-line) had the same problem as well, but I had a different error that was due to it struggling to find the class. 
<details>
~/stem-projects/company-repos/lockbook(smail/infra/kotlin-interface-tests-no-sdk) » java -cp /home/smail-barkouch/stem-projects/company-repos/lockbook/clients/android/app/src/test/java/app/lockbook/:/home/smail-barkouch/Downloads/junit-4.12.jar:/home/smail-barkouch/Downloads/hamcrest-core-1.3.jar org.junit.runner.JUnitCore app.lockbook.SyncAllTest         
JUnit version 4.12
.E
Time: 0.003
There was 1 failure:
1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
java.lang.IllegalArgumentException: Could not find class [app.lockbook.SyncAllTest]
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:102)
        at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
        at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
Caused by: java.lang.ClassNotFoundException: app.lockbook.SyncAllTest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.junit.internal.Classes.getClass(Classes.java:16)
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
        ... 4 more

FAILURES!!!
Tests run: 1,  Failures: 1
<details>

The error above is just one of many different attempts to get the command working.

Another contender was the adb, it could be used to run the tests pretty seamlessly, and without having to install the entire android sdk, but there was one big problem. The adb required that an android device would be connect and this would defeat the purpose of the tests.

As of right now there are no contenders for running the test besides gradle, which requires the sdk. We could transition to a lightweight type of sdk and that could reduce the build times.
